### ISSUE TITLE
Kinect v2 for model fit

### ISSUE THREAD

**Issue by Gzzgz** [jonathantompson/ModelFit#3]
hello，
       Hello, I would like to ask how to set up the kinectV2 parameters formodel-fit? And I would like to ask how compute this ：

const float OpenNIFuncs::fHFOV_primesense_109 = 1.0144686707507438 * 0.97;  // kinect v1
const float OpenNIFuncs::fVFOV_primesense_109 = 0.78980943449644714 * 0.98;  // kinect v1

const float OpenNIFuncs::fx = 588.03;
const float OpenNIFuncs::fy = 587.07;

Thanks！

**Comment by jonathantompson** [comment]
Firstly, I would do a quick google search to see if anyone else has measured the FOV and center of projection of the new Kinect. I'm sure this data is somewhere on the internet.

Failing that, you can try using any of the standard calibration toolboxes ([this one is a good option](http://www.vision.caltech.edu/bouguetj/calib_doc/)) to measure the intrinsic parameters of the depth camera. Hopefully the new Kinect allows you to get raw IR, because this (with a checkerboard calibration pattern) is the easiest way to get back these calibration parameters.

**Comment by Gzzgz** [comment]
Hi,
   OK, Thx. But I use kinect2 parameters as follows: 

const double OpenNIFuncs::fHFOV_kinect_ = 70 * 3.14159265f / 180.0f ; 
const double OpenNIFuncs::fVFOV_kinect_ = 60 * 3.14159265f / 180.0f ; 

const float OpenNIFuncs::fHFOV_primesense_109 = 70*3.14159265f/180.0f ;  // kinect v2
const float OpenNIFuncs::fVFOV_primesense_109 = 60*3.14159265f/180.0f ;  // kinect v2

const float OpenNIFuncs::fx = 457.0f; //588.03;
const float OpenNIFuncs::fy = 415.69f; //587.07;
const float OpenNIFuncs::fu = 320;
const float OpenNIFuncs::fv = 240;

this means K2(1920x1080->paded:1920x1440 and then downsample by 3 : 640x480),

calibrated Kinect v2 (I use 2 kinects V2 ,by BOX no Icosahedron ),the result as follows:
the pngs show that second depth-png will be deviated after calibrated
and the calibrated result is that has a gap between with 2 point clouds.

How to solve this ？  thx very much.
